In [3]:
# Importing Required Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
%matplotlib inline

### Import the dataset

In [4]:
# The functions below will download the dataset

import asyncio
import aiohttp

async def download(url, filename):
    async with aiohttp.ClientSession() as session:
        async with session.get(url) as response:
            if response.status == 200:
                with open(filename, 'wb') as f:
                    f.write(await response.read())
                    
                    
file_path= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-Coursera/laptop_pricing_dataset_mod2.csv"

await download(file_path, "laptops.csv")
file_name="laptops.csv"

# Import the file to a pandas dataframe.
df = pd.read_csv(file_name, header=0)
df.head()

,Unnamed: 0.1,Unnamed: 0,Manufacturer,Category,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price,Price-binned,Screen-Full_HD,Screen-IPS_panel
0,0,0,Acer,4,2,1,5,14.0,0.551724,8,256,3.52800,978,Low,0,1
1,1,1,Dell,3,1,1,3,15.6,0.689655,4,256,4.85100,634,Low,1,0
2,2,2,Dell,3,1,1,7,15.6,0.931034,8,256,4.85100,946,Low,1,0
3,3,3,Dell,4,2,1,5,13.3,0.551724,8,128,2.69010,1244,Low,0,1
4,4,4,HP,4,2,1,7,15.6,0.620690,8,256,4.21155,837,Low,1,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0.1      238 non-null    int64
 1   Unnamed: 0        238 non-null    int64
 2   Manufacturer      238 non-null    object
 3   Category          238 non-null    int64
 4   GPU               238 non-null    int64
 5   OS                238 non-null    int64
 6   CPU_core          238 non-null    int64
 7   Screen_Size_inch  238 non-null    float64
 8   CPU_frequency     238 non-null    float64
 9   RAM_GB            238 non-null    int64
 10  Storage_GB_SSD    238 non-null    int64
 11  Weight_pounds     238 non-null    float64
 12  Price             238 non-null    int64
 13  Price-binned      238 non-null    object
 14  Screen-Full_HD    238 non-null    int64
 15  Screen-IPS_panel  238 non-null    int64
dtypes: float64(3), int64(11), object(2)
memory usage: 29.9+ KB